### ISSUE TITLE
lint 'breakOnError' fails with incorrect exit code

### ISSUE THREAD

**Issue by sragu** [emgeee/gulp-standard#13]
Though it reports failure, the command completes successfully. It should return exit code other than zero.

```
அ gulp lintjs
[10:02:39] Using gulpfile ~/dev/playground/skeleton-web/gulpfile.js
[10:02:40] Starting 'lintjs'...
Standard linter results
======================================

[10:02:40] Finished 'lintjs' after 20 ms
src/lib/bootstrap.js
line 3:8    "_" is defined but never used
✖ 1 errors    ⚠ 0 warnings

அ echo $?
0
```

This is a bit of trouble of CI.

**Comment by emgeee** [comment]
If I understand your issue correctly, it sounds like it's up to you to listen for the `error` event and kill the task yourself.
