### ISSUE TITLE
Throws EPEERINVALID with standard 6: breaks shrinkwrap

### ISSUE THREAD

**Issue by razor-x** [emgeee/gulp-standard#14]
Given the following in `package.json`,

```
"devDependencies": {
  "gulp-standard": "^5.2.2",
  "standard": "^6.0.3"
}
```

`npm install` throws:

```
npm WARN EPEERINVALID eslint-config-standard-jsx@1.1.0 requires a peer of eslint@^2.0.0-rc.0 but none was installed.
```

This breaks `npm shrinkwrap --dev` with

```
peer invalid: eslint@^2.0.0-rc.0, required by eslint-config-standard-jsx@1.1.0
```

My environment:

```
$ npm version
{ 'test-pkg': '1.0.0',
  npm: '3.3.12',
  ares: '1.10.1-DEV',
  http_parser: '2.6.0',
  icu: '56.1',
  modules: '47',
  node: '5.5.0',
  openssl: '1.0.2e',
  uv: '1.8.0',
  v8: '4.6.85.31',
  zlib: '1.2.8' }
```

**Comment by razor-x** [comment]
Just a follow up. Looks like standard 6 is only about a day old :zap: Just happened to be setting up some new things across the release when this broke.

Anyway, might be as simple as bumping the dependency to 6 here as I'm sure is planned. Tried it locally and tested with `"file:../gulp-standard"` without the error.

**Comment by emgeee** [comment]
@razor-x I just merged your PR can you confirm that your issue has been fixed?

**Comment by razor-x** [comment]
Seems to be working now :cool:
