### ISSUE TITLE
Using Custom Parsers

### ISSUE THREAD

**Issue by DaAwesomeP** [emgeee/gulp-standard#24]
I use babel and therefore need to use `babel-eslint`. The standard docs [shows a way to do this](https://github.com/feross/standard#can-i-use-a-custom-js-parser-for-bleeding-edge-es-next-support). Will this work with `gulp-standard`?

**Comment by emgeee** [comment]
Yep, it should!

**Comment by DaAwesomeP** [comment]
Thanks!
