### ISSUE TITLE
Reporter blocks piping even on success

### ISSUE THREAD

**Issue by lawlesscreation** [emgeee/gulp-standard#26]
I've just been trying to add gulp-standard to an existing project that uses Gulp but the reporter seems to block further tasks even when the files were valid:

```
gulp.task('js', function () {
  return gulp.src([
    'js/*.js'
  ])
  .pipe(standard())
  .pipe(standard.reporter('default', {
    breakOnError: true,
    breakOnWarning: false,
    quiet: false
  }))
  .pipe(concat('scripts.min.js'))
  .pipe(uglify())
  .pipe(gulp.dest('dest/js'))
})
```

I get `Standard linter results: ✔ All OK!` but no file is created. Standard report errors successfully and the file is created when commenting out the reporter - but with the reporter it just seems to block further tasks.

Has anyone else had any problems with using gulp-standard to pipe through further tasks like this?

```
Node: v6.9.2
npm: 3.10.9
```

**Comment by bdekok** [comment]
I'm working on the same project as @lawlesscreation and I've been experiencing the same pain on his branch.  So it seems it is not limited to his machine, we can share our package.json if you'd like

**Comment by lawlesscreation** [comment]
A workable option is to move the reporter to the last pipe:

```
gulp.task('js', function () {
  return gulp.src([
    'js/*.js'
  ])
  .pipe(standard())
  .pipe(concat('scripts.min.js'))
  .pipe(uglify())
  .pipe(gulp.dest('dest/js'))
  .pipe(standard.reporter('default', {
    breakOnError: true,
    breakOnWarning: false,
    quiet: false
  }))
})
```

Not ideal but it works.

**Comment by turakvlad** [comment]
I have the same issue.

**Comment by stephenlacy** [comment]
I can check into this - can someone create a simple reproduction repo? If not I'll figure one out

**Comment by turakvlad** [comment]
@stevelacy I've created the repo - https://github.com/turakvlad/gulp-standard-bug. I've commented the `gulp-standard` in 42 - 46 lines in my `gulpfile.js`. If you uncomment it and run `gulp --layout=dashboard`, the Gulp will not copy the `js` files to the `dist` directory, because the `standard.reporter` brakes the pipe.

I've examined the code yesterday and it seems that the problem is in `default` reporter (`Stylish`) that is called here (`node_modules/gulp-standard/index.js`):
```
gulpStandard.reporter = function (reporter, opts) {
  // Load default reporter
  if (reporter === 'default') return defaultReporter(opts)

  // Load reporter from function
  if (typeof reporter === 'function') return reporter(opts)

  // load built-in reporters
  if (typeof reporter === 'string') {
    try {
      return require('gulp-standard/reporters/' + reporter)(opts)
    } catch (err) {}
  }

  // load full-path or module reporters
  if (typeof reporter === 'string') {
    try {
      return require(reporter)(opts)
    } catch (err) {}
  }
}
```
I think, that `Stylish` doesn't return the stream correctly here (`node_modules/gulp-standard/reporters/stylish.js`):

```
  return through2.obj(function (file, enc, cb) {
    if (file.isNull()) {
      return cb(null, file)
    }

    if (file.isStream()) {
      return cb(new gutil.PluginError(PLUGIN_NAME, 'Streams are not supported!'))
    }

    // Report file specific stuff only when there are some errors/warnings
    if (file.standard && (file.standard.errorCount || file.standard.warningCount)) {
      totalErrorCount += file.standard.errorCount
      totalWarningCount += file.standard.warningCount

      console.log(reportFile(file.path, file.standard))
    }

    cb()
  })
    .on('end', function () {
      reportFooter()

      // If user wants gulp to break execution on reported errors or warnings
      if (totalErrorCount && options.breakOnError) {
        this.emit('error', new gutil.PluginError(PLUGIN_NAME, 'Linter errors occurred!'))
      }
      if (totalWarningCount && options.breakOnWarning) {
        this.emit('error', new gutil.PluginError(PLUGIN_NAME, 'Linter warnings occurred!'))
      }
    })
```

Thanks a lot for help!

**Comment by stephenlacy** [comment]
Opened #27 which should fix this.
@turakvlad make sure that you remove `breakOnError` from your code before testing as that will break the process.
