### ISSUE TITLE
Add stylish reporters

### ISSUE THREAD

**Issue by stephenlacy** [emgeee/gulp-standard#3]
Example:
(jshint) ![](https://raw.githubusercontent.com/sindresorhus/jshint-stylish/master/screenshot.png)

**Comment by leomelin** [comment]
I hope this helps a bit https://github.com/leomelin/gulp-standard-reporter

**Comment by stevelacy** [comment]
@leomelin instead of submitting a PR and contributing to a gulp plugin you created a duplicate plugin?
Two plugins should not do the same thing, or the newer one will be blacklisted.

**Comment by leomelin** [comment]
It's not a duplicate, cause it doesn't lint, it just reports the file.standard output similarly to [jshints-stylish](https://github.com/sindresorhus/jshint-stylish). I was planning to make it as part of your plugin, but decided to go this way. I can merge these two and send a PR, ok?

**Comment by stephenlacy** [comment]
Added, thanks @leomelin!
