### ISSUE TITLE
Is there functionality to run --fix?

### ISSUE THREAD

**Issue by m-orsh** [emgeee/gulp-standard#33]
Any way to run the standard fixer similar to `standard --fix` ?

**Comment by gucong3000** [comment]
yes. #31

**Comment by gucong3000** [comment]
Repeat with other #30

**Comment by marknotton** [comment]
Could you elaborate a little on how too apply the --fix function please?

gulp-standard is detecting errors, but not fixing them. I can't figure out how to apply it as an option and it's not fixing formatting errors automatically. This doesn't work:

```
return gulp.src('myScripts.js')
  .pipe(standard({fix: true}))
  .pipe(standard.reporter('default', {
    fix: true,
  }))
```

**Comment by gucong3000** [comment]
> Could you elaborate a little on how too apply the --fix function please?
```js
return gulp.src('myScripts.js')
  .pipe(standard({fix: true}))
  .pipe(standard.reporter('default'))
```
> gulp-standard is detecting errors, but not fixing them.

Not all ESLint rules can be automatically fixed. See here: https://eslint.org/docs/rules/
